name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag data-news:latest
      
    - name: Get current time
      id: current-time
      uses: josStorer/get-current-time@v2.0.2
      with:
        format: YYYY-MM-DD-HH-mm-ss
        utcOffset: "+02:00"

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v3
      with:
        file: ./Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/rso-data-news:${{ steps.current-time.outputs.formattedTime }}
          ${{ secrets.DOCKERHUB_USERNAME }}/rso-data-news:latest
